# Generated by Django 4.2 on 2023-04-04 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 4, 4, 11, 36, 25, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
