# Generated by Django 4.2 on 2023-04-04 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_created_alter_blog_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 11, 49, 25, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 11, 49, 25, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Core',
        ),
    ]
