# Generated by Django 4.2 on 2023-04-04 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_created_alter_blog_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 4, 4, 13, 37, 19, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 4, 4, 13, 37, 19, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 13, 37, 19, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 13, 37, 19, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 4, 4, 13, 37, 19, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 4, 4, 13, 37, 19, tzinfo=datetime.timezone.utc))),
                ('author', models.ManyToManyField(to='core.author')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
